### PR TITLE
Feedback icons for O2 new

### PR DESCRIPTION
**Pull request by yceballost**
https://jira.tid.es/browse/ANDROID-14848

### :goal_net: What's the goal?
Replace custom animation assets for O2-New skin

### :test_tube: How can I test this?
| Old | New |
|---|---|
| Foto seleccionada | Multimedia (5) |
| Foto seleccionada (1) | Multimedia |
| Foto seleccionada (2) | Multimedia (3) |

### CODE REVIEW

**Comment by dpastor** [comment]
Wow! Thanks a lot @yceballost !!! It's correct, but let me just confirm we can merge this now to include this on 24.6 or not.

Thanks again!

**Review by dpastor — APPROVED** [review]
👍

**Review by juangardi21 — APPROVED** [review]
LGTM 👍🏼

**Comment by nimeacuerdo** [comment]
@dpastor does this require a 12.x release because of potential issues of having this over the already breaking changes in 13.x?

**Comment by dpastor** [comment]
> @dpastor does this require a 12.x release because of potential issues of having this over the already breaking changes in 13.x?

I think no, breaking changes in 13.0.0 are very simple (related to snackbars, where a null can be passed), we should be able to publish it as a 13.1.0.

**Pull request merged**
