### PR TITLE
ANDROID-11150 Add informative and action sheet component types

### PR DESCRIPTION
**Pull request by gmerinojimenez**
### :goal_net: What's the goal?
[ANDROID-11150](https://jira.tid.es/browse/ANDROID-11150)
Adding Informative and Action sheet types as described [here](https://www.figma.com/file/nxToAYk7FGC86TS0mY61TU/Sheet?node-id=1960%3A11572)

### :construction: How do we do it?
* Adding the models and the adapters to display the new two component types.
* Adding them also to the catalog.

### ☑️ Checks
- [X] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.

### :test_tube: How can I test this?

https://user-images.githubusercontent.com/4595241/196216483-5c5eaff6-7578-428d-aae3-78f111b1975d.mp4

https://user-images.githubusercontent.com/4595241/196216878-5ae6dad9-0e28-4281-bba0-bd453db26438.mp4

### CODE REVIEW

**Review by dagonco — APPROVED** [review]
Great job, thanks so much :D

**Comment by AnaMontes11** [comment]
In the information sheets, I see the list items too close together. The distances within the list content do not follow the specs definition

**Comment by gmerinojimenez** [comment]
> In the Informative Sheets, I see the list items too close together. The distances within the list content do not follow the [specs ](https://www.figma.com/file/nxToAYk7FGC86TS0mY61TU/Sheet?node-id=1960%3A11572) definition. 

my bad, I misunderstood that one, let me change it :)

**Comment by AnaMontes11** [comment]
In the Actions Sheet, review the distances set out in the [specs](https://www.figma.com/file/nxToAYk7FGC86TS0mY61TU/Sheet?node-id=1960%3A13985). I think the first action label is too close to the description.
 4 px and the action label paddings need to be added. I would rename them as "Action label or Action label title" instead of "Title" or "Another" for greater clarity.

**Review by dpastor — APPROVED** [review]
👍

**Pull request merged**
