### PR TITLE
ANDROID-14716 - Add space to progress bar in button

### PR DESCRIPTION
**Pull request by DevPabloGarcia**
### :goal_net: What's the goal?
Don't cut text in loading state in buttons

If the text of the normal state and the loading state in a link button is the same, when we are showing the loading button, the text doesn't fit, showing three dots.

❗ There is only one file changed, Button.kt. The rest are baseline updates ❗ 

### :construction: How do we do it?
* When calculate button width, add progress bar size and space

### ☑️ Checks
- [x] I updated the documentation, including readmes and wikis. If this is a breaking change, tag the PR with "Breaking Change" label and remember to include breaking change migration guide in release notes where this version is released.
- [x] Tested with dark mode.
- [x] Tested with API 24.

### :test_tube: How can I test this?
_If it cannot be tested explain why._
- [x] 🖼️ Screenshots/Videos
- [x] Mistica App QR or download link
- [ ] Reviewed by Mistica design team

https://github.com/Telefonica/mistica-android/assets/42326032/a072ed3e-018f-4df7-9cde-3f430bfb6a3c

### CODE REVIEW

**Review by pmartinbTEF — APPROVED** [review]
LGTM

**Review by jdelga — COMMENTED** [review]
I think that the only updated screenshot should be the one that is a loading button (has a Loading text)

As you can see in the generated screenshots, all buttons have been updated to have a higher width. However, none of the screenshots belong to "Loading Button", as it is not defined in the tested button parameters:

https://github.com/Telefonica/mistica-android/blob/432fb54363ad0252eabe4b79f482d56f67b8649b/library/src/test/java/com/telefonica/mistica/compose/button/ButtonKtTest.kt#L48

I think that the bounding box that should be updated is only for the case of a loading button, which is the one that has a secondary text, which causes the bug.

https://github.com/Telefonica/mistica-android/blob/432fb54363ad0252eabe4b79f482d56f67b8649b/library/src/main/java/com/telefonica/mistica/compose/button/Button.kt#L63

WDYT ?

Adit: 

Also, I think the case which is the one that has a loading text larger than standard text is not covered yet:

loading_true

**Comment by DevPabloGarcia** [comment]
> I think that the only updated screenshot should be the one that is a loading button (has a Loading text)
> 
> As you can see in the generated screenshots, all buttons have been updated to have a higher width. However, none of the screenshots belong to "Loading Button", as it is not defined in the tested button parameters:
> 
> https://github.com/Telefonica/mistica-android/blob/432fb54363ad0252eabe4b79f482d56f67b8649b/library/src/test/java/com/telefonica/mistica/compose/button/ButtonKtTest.kt#L48
> 
> I think that the bounding box that should be updated is only for the case of a loading button, which is the one that has a secondary text, which causes the bug.
> 
> https://github.com/Telefonica/mistica-android/blob/432fb54363ad0252eabe4b79f482d56f67b8649b/library/src/main/java/com/telefonica/mistica/compose/button/Button.kt#L63
> 
> WDYT ?
> 
> Adit:
> 
> Also, I think the case with a loading text larger than standard text is not covered yet:
> 
> drawing

You are right! Changed.

The case when the loading text is longer than normal text will be implemented in the future. I have to check with team if we really need to cover this behaviour for now. Thinking about a possible solution, we need to calculate the width before painting the button. It maybe cause an overprograming.

**Review by jdelga — APPROVED** [review]
So cool! Thanks! ❤️

**Review by yceballost — APPROVED** [review]

**Review by yceballost — APPROVED** [review]

**Pull request merged**
